In [178]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [179]:
import pandas as pd
import numpy  as np

In [180]:
data_preprocessed=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/df_preprocessed.csv')
data_preprocessed.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Month Value,Day of the Week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,0,0,0,1,7,1,289,36,33,239.554,30,0,2,1,4
1,0,0,0,0,7,1,118,13,50,239.554,31,0,1,0,0
2,0,0,0,1,7,2,179,51,38,239.554,31,0,0,0,2
3,1,0,0,0,7,3,279,5,39,239.554,24,0,2,0,4
4,0,0,0,1,7,3,289,36,33,239.554,30,0,2,1,2

In [181]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [182]:
target=np.where(data_preprocessed['Absenteeism Time in Hours']>data_preprocessed['Absenteeism Time in Hours'].median(),1,0)
target

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0])

In [183]:
data_preprocessed['Exessive Absenteesism']=target
data_preprocessed.shape

(700, 16)

In [184]:
target.sum()/target.shape[0]

np.float64(0.45571428571428574)

In [185]:
data_with_target=data_preprocessed.drop(['Absenteeism Time in Hours', 'Day of the Week', 'Daily Work Load Average', 'Distance to Work'], axis=1)

data_with_target.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Month Value,Transportation Expense,Age,Body Mass Index,Education,Children,Pets,Exessive Absenteesism
0,0,0,0,1,7,289,33,30,0,2,1,1
1,0,0,0,0,7,118,50,31,0,1,0,0
2,0,0,0,1,7,179,38,31,0,0,0,0
3,1,0,0,0,7,279,39,24,0,2,0,1
4,0,0,0,1,7,289,33,30,0,2,1,0

In [186]:
data_with_target.shape

(700, 12)

In [187]:
data_with_target.iloc[:,:-1]

,Reason_1,Reason_2,Reason_3,Reason_4,Month Value,Transportation Expense,Age,Body Mass Index,Education,Children,Pets
0,0,0,0,1,7,289,33,30,0,2,1
1,0,0,0,0,7,118,50,31,0,1,0
2,0,0,0,1,7,179,38,31,0,0,0
3,1,0,0,0,7,279,39,24,0,2,0
4,0,0,0,1,7,289,33,30,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...
695,1,0,0,0,5,179,40,22,1,2,0
696,1,0,0,0,5,225,28,24,0,1,2
697,1,0,0,0,5,330,28,25,1,0,0
698,0,0,0,1,5,235,32,25,1,0,0
699,0,0,0,1,5,291,40,25,0,1,1

In [188]:
unscaled_inputs=data_with_target.iloc[:,:-1]

In [189]:
from sklearn.preprocessing import StandardScaler
absenteeism_scaler=StandardScaler()

In [190]:
from sklearn.base import BaseEstimator,TransformerMixin
class CustomScaler(BaseEstimator,TransformerMixin):
  def __init__(self,columns,copy=True,with_mean=True,with_std=True):
    self.scaler=StandardScaler(copy=copy,with_mean=with_mean,with_std=with_std)
    self.columns=columns
    self.mean_=None
    self.var_=None
  def fit(self,X,y=None):
    self.scaler.fit(X[self.columns],y)
    self.mean_=np.mean(X[self.columns])
    self.var_=np.var(X[self.columns])
  def transform(self,X,y=None,copy=None):
    init_col_order=X.columns
    X_scaled=pd.DataFrame(self.scaler.transform(X[self.columns]),columns=self.columns)
    x_not_scaled=X.loc[:,~X.columns.isin(self.columns)]
    return pd.concat([x_not_scaled,X_scaled],axis=1)[init_col_order]

In [191]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [192]:
column_to_scale=['Month Value','Transportation Expense', 'Age', 'Body Mass Index','Children', 'Pets']

In [193]:
absenteeism_scaler=CustomScaler(column_to_scale)

In [194]:
absenteeism_scaler.fit(unscaled_inputs)

/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:4006: FutureWarning: The behavior of DataFrame.var with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return var(axis=axis, dtype=dtype, out=out, ddof=ddof, **kwargs)

In [195]:
scaled_inputs=absenteeism_scaler.transform(unscaled_inputs)

In [196]:
scaled_inputs.shape

(700, 11)

In [197]:
scaled_inputs

,Reason_1,Reason_2,Reason_3,Reason_4,Month Value,Transportation Expense,Age,Body Mass Index,Education,Children,Pets
0,0,0,0,1,0.182726,1.005844,-0.536062,0.767431,0,0.880469,0.268487
1,0,0,0,0,0.182726,-1.574681,2.130803,1.002633,0,-0.019280,-0.589690
2,0,0,0,1,0.182726,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690
3,1,0,0,0,0.182726,0.854936,0.405184,-0.643782,0,0.880469,-0.589690
4,0,0,0,1,0.182726,1.005844,-0.536062,0.767431,0,0.880469,0.268487
...,...,...,...,...,...,...,...,...,...,...,...
695,1,0,0,0,-0.388293,-0.654143,0.562059,-1.114186,1,0.880469,-0.589690
696,1,0,0,0,-0.388293,0.040034,-1.320435,-0.643782,0,-0.019280,1.126663
697,1,0,0,0,-0.388293,1.624567,-1.320435,-0.408580,1,-0.919030,-0.589690
698,0,0,0,1,-0.388293,0.190942,-0.692937,-0.408580,1,-0.919030,-0.589690
699,0,0,0,1,-0.388293,1.036026,0.562059,-0.408580,0,-0.019280,0.268487

In [198]:
from sklearn.model_selection import train_test_split

In [199]:
train_test_split(scaled_inputs,target)

[     Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
 4           0         0         0         1     0.182726
 325         0         0         0         0     1.324766
 0           0         0         0         1     0.182726
 675         0         0         1         0    -0.388293
 371         1         0         0         0    -1.244823
 ..        ...       ...       ...       ...          ...
 503         0         0         0         1     0.753746
 637         1         0         0         0    -0.959313
 406         0         0         0         0    -0.959313
 547         0         0         0         1     1.324766
 234         0         0         0         1    -0.102784

      Transportation Expense       Age  Body Mass Index  Education  Children  \
 4                  1.005844 -0.536062         0.767431          0  0.880469
 325                1.624567 -1.320435        -0.408580          1 -0.919030
 0                  1.005844 -0.536062         0.767431          0  0.880469
 675                0.040034  0.718933         0.297027          1  0.880469
 371                0.040034 -1.320435        -0.643782          0 -0.019280
 ..                      ...       ...              ...        ...       ...
 503                0.040034 -1.320435        -0.643782          0 -0.019280
 637                0.040034 -1.320435        -0.643782          0 -0.019280
 406                0.356940  0.718933        -0.878984          0 -0.919030
 547                0.040034 -1.320435        -0.643782          0 -0.019280
 234                1.005844  1.973929         2.178644          0 -0.919030

          Pets
 4    0.268487
 325 -0.589690
 0    0.268487
 675  1.126663
 371  1.126663
 ..        ...
 503  1.126663
 637  1.126663
 406 -0.589690
 547  1.126663
 234  1.126663

 [525 rows x 11 columns],
      Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
 546         1         0         0         0     1.324766
 531         1         0         0         0     1.039256
 63          0         0         0         1     1.039256
 621         0         0         0         1    -0.959313
 335         0         1         0         0     1.324766
 ..        ...       ...       ...       ...          ...
 300         0         0         0         0     1.039256
 655         1         0         0         0    -0.673803
 247         0         0         0         1     0.182726
 416         0         0         0         1    -0.673803
 548         0         0         0         0     1.324766

      Transportation Expense       Age  Body Mass Index  Education  Children  \
 546               -1.574681  0.091435         0.297027          0 -0.919030
 531                0.040034 -1.320435        -0.643782          0 -0.019280
 63                -1.574681  0.091435         0.297027          0 -0.919030
 621                0.387122  1.660180         1.237836          0  0.880469
 335                0.568211 -0.065439        -0.878984          0  2.679969
 ..                      ...       ...              ...        ...       ...
 300                0.190942  1.032682         2.649049          0 -0.019280
 655               -1.574681  0.091435         0.297027          0 -0.919030
 247                1.005844 -0.536062         0.767431          0  0.880469
 416                0.387122  1.660180         1.237836          0  0.880469
 548                1.036026  0.562059        -0.408580          0 -0.019280

          Pets
 546 -0.589690
 531  1.126663
 63  -0.589690
 621  0.268487
 335 -0.589690
 ..        ...
 300 -0.589690
 655 -0.589690
 247  0.268487
 416  0.268487
 548  0.268487

 [175 rows x 11 columns],
 array([0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
        0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
        1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0,
        0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
        1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0,
        0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
        0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1,
        1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1,
        0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0,
        1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0,
        1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0,
        0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
        0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
        0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
        1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,
        1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
        0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0,
        1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1,
        0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
        1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0]),
 array([1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
        0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1,
        0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
        1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
        1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0,
        0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
        0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0])]

In [200]:
x_train,x_test,y_train,y_test=train_test_split(scaled_inputs,target,train_size=0.8,random_state=20)

In [201]:
print(x_train.shape,y_train.shape)

(560, 11) (560,)

In [202]:
print(x_test.shape,y_test.shape)

(140, 11) (140,)

In [203]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [204]:
reg=LogisticRegression()

In [205]:
reg.fit(x_train,y_train)

LogisticRegression()

In [206]:
reg.score(x_train,y_train)

0.7732142857142857

In [207]:
model_outputs=reg.predict(x_train)
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 0])

In [208]:
model_outputs==y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True, False,
        True, False,  True, False,  True,  True,  True,  True, False,
       False, False,  True,  True, False,  True, False,  True,  True,
        True, False,  True, False,  True, False,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True, False,
       False,  True,  True,  True,  True,  True,  True,  True, False,
        True, False,  True, False,  True,  True,  True,  True, False,
        True, False, False,  True,  True,  True,  True,  True, False,
       False, False,  True, False,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True, False, False,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True, False, False,
       False,  True,  True,  True,  True, False,  True, False,  True,
        True,  True,  True,  True,  True,  True, False,  True, False,
       False,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True, False, False,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True, False,
       False,  True,  True,  True,  True,  True, False,  True, False,
        True,  True,  True, False, False,  True,  True,  True, False,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True, False,  True,
        True, False,  True, False,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True, False,  True,  True, False,  True, False,
        True,  True,  True,  True,  True, False, False,  True,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
       False,  True,  True,  True, False, False,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True, False, False,  True,  True,
       False,  True,  True,  True,  True,  True,  True, False, False,
        True,  True, False,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True, False,  True,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True, False,  True,  True,
       False, False, False,  True,  True, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
       False,  True])

In [209]:
np.sum(model_outputs==y_train)

np.int64(433)

In [210]:
model_outputs.shape[0]

560

In [211]:
np.sum(model_outputs==y_train)/model_outputs.shape[0]

np.float64(0.7732142857142857)

In [212]:
reg.intercept_

array([-1.6469898])

In [213]:
reg.coef_

array([[ 2.80000644,  0.95174778,  3.1140605 ,  0.83835931,  0.15897713,
         0.60513709, -0.16990589,  0.27998236, -0.21017416,  0.34842434,
        -0.27721907]])

In [214]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [215]:
feature_name=unscaled_inputs.columns.values

In [216]:
summary_table=pd.DataFrame(columns=['Feature Name'],data=feature_name)
summary_table['Coefficient']=np.transpose(reg.coef_)
summary_table

              Feature Name  Coefficient
0                 Reason_1     2.800006
1                 Reason_2     0.951748
2                 Reason_3     3.114061
3                 Reason_4     0.838359
4              Month Value     0.158977
5   Transportation Expense     0.605137
6                      Age    -0.169906
7          Body Mass Index     0.279982
8                Education    -0.210174
9                 Children     0.348424
10                    Pets    -0.277219

In [217]:
summary_table.index=summary_table.index+1
summary_table.loc[0]=['Intercept',reg.intercept_[0]]
summary_table=summary_table.sort_index()
summary_table

              Feature Name  Coefficient
0                Intercept    -1.646990
1                 Reason_1     2.800006
2                 Reason_2     0.951748
3                 Reason_3     3.114061
4                 Reason_4     0.838359
5              Month Value     0.158977
6   Transportation Expense     0.605137
7                      Age    -0.169906
8          Body Mass Index     0.279982
9                Education    -0.210174
10                Children     0.348424
11                    Pets    -0.277219

In [218]:
summary_table['Odds Ratio']=np.exp(summary_table.Coefficient)
summary_table

              Feature Name  Coefficient  Odds Ratio
0                Intercept    -1.646990    0.192629
1                 Reason_1     2.800006   16.444753
2                 Reason_2     0.951748    2.590233
3                 Reason_3     3.114061   22.512270
4                 Reason_4     0.838359    2.312570
5              Month Value     0.158977    1.172311
6   Transportation Expense     0.605137    1.831503
7                      Age    -0.169906    0.843744
8          Body Mass Index     0.279982    1.323106
9                Education    -0.210174    0.810443
10                Children     0.348424    1.416833
11                    Pets    -0.277219    0.757888

In [219]:
summary_table.sort_values('Odds Ratio',ascending=False)

              Feature Name  Coefficient  Odds Ratio
3                 Reason_3     3.114061   22.512270
1                 Reason_1     2.800006   16.444753
2                 Reason_2     0.951748    2.590233
4                 Reason_4     0.838359    2.312570
6   Transportation Expense     0.605137    1.831503
10                Children     0.348424    1.416833
8          Body Mass Index     0.279982    1.323106
5              Month Value     0.158977    1.172311
7                      Age    -0.169906    0.843744
9                Education    -0.210174    0.810443
11                    Pets    -0.277219    0.757888
0                Intercept    -1.646990    0.192629

In [220]:
reg.score(x_test,y_test)

0.75

In [222]:
predict_proba=reg.predict_proba(x_test)
predict_proba

array([[0.71342516, 0.28657484],
       [0.5873216 , 0.4126784 ],
       [0.44016153, 0.55983847],
       [0.78163061, 0.21836939],
       [0.08407928, 0.91592072],
       [0.3348226 , 0.6651774 ],
       [0.29971206, 0.70028794],
       [0.13112385, 0.86887615],
       [0.78627908, 0.21372092],
       [0.74906578, 0.25093422],
       [0.49395555, 0.50604445],
       [0.22492002, 0.77507998],
       [0.07135527, 0.92864473],
       [0.73173354, 0.26826646],
       [0.30957854, 0.69042146],
       [0.54726422, 0.45273578],
       [0.55051921, 0.44948079],
       [0.53926379, 0.46073621],
       [0.40197149, 0.59802851],
       [0.05365482, 0.94634518],
       [0.70030387, 0.29969613],
       [0.78163061, 0.21836939],
       [0.42028246, 0.57971754],
       [0.42028246, 0.57971754],
       [0.24801464, 0.75198536],
       [0.74567806, 0.25432194],
       [0.51026557, 0.48973443],
       [0.8569309 , 0.1430691 ],
       [0.20365204, 0.79634796],
       [0.78163061, 0.21836939],
       [0.63052323, 0.36947677],
       [0.32086805, 0.67913195],
       [0.31491675, 0.68508325],
       [0.47129209, 0.52870791],
       [0.78163061, 0.21836939],
       [0.46494772, 0.53505228],
       [0.77855256, 0.22144744],
       [0.26326831, 0.73673169],
       [0.59499242, 0.40500758],
       [0.39495703, 0.60504297],
       [0.78927881, 0.21072119],
       [0.54772892, 0.45227108],
       [0.76250674, 0.23749326],
       [0.60152822, 0.39847178],
       [0.17236423, 0.82763577],
       [0.43228078, 0.56771922],
       [0.30879153, 0.69120847],
       [0.71342516, 0.28657484],
       [0.7807653 , 0.2192347 ],
       [0.7967288 , 0.2032712 ],
       [0.42365518, 0.57634482],
       [0.67045762, 0.32954238],
       [0.3348226 , 0.6651774 ],
       [0.73062472, 0.26937528],
       [0.16676318, 0.83323682],
       [0.56515855, 0.43484145],
       [0.11634129, 0.88365871],
       [0.76874913, 0.23125087],
       [0.66566251, 0.33433749],
       [0.65548603, 0.34451397],
       [0.30084899, 0.69915101],
       [0.3450062 , 0.6549938 ],
       [0.70755417, 0.29244583],
       [0.20813948, 0.79186052],
       [0.79247768, 0.20752232],
       [0.73161991, 0.26838009],
       [0.91289589, 0.08710411],
       [0.77855256, 0.22144744],
       [0.26784781, 0.73215219],
       [0.69463474, 0.30536526],
       [0.77855256, 0.22144744],
       [0.7099211 , 0.2900789 ],
       [0.09556159, 0.90443841],
       [0.53934229, 0.46065771],
       [0.39824649, 0.60175351],
       [0.78163061, 0.21836939],
       [0.22662722, 0.77337278],
       [0.26823402, 0.73176598],
       [0.25833667, 0.74166333],
       [0.32849848, 0.67150152],
       [0.75418947, 0.24581053],
       [0.92381866, 0.07618134],
       [0.76874913, 0.23125087],
       [0.24733029, 0.75266971],
       [0.56565144, 0.43434856],
       [0.87778155, 0.12221845],
       [0.29566831, 0.70433169],
       [0.42028246, 0.57971754],
       [0.75875643, 0.24124357],
       [0.32086805, 0.67913195],
       [0.82487741, 0.17512259],
       [0.84951629, 0.15048371],
       [0.77378438, 0.22621562],
       [0.73161991, 0.26838009],
       [0.74906578, 0.25093422],
       [0.14943734, 0.85056266],
       [0.70405613, 0.29594387],
       [0.23705541, 0.76294459],
       [0.75656954, 0.24343046],
       [0.78200879, 0.21799121],
       [0.37670539, 0.62329461],
       [0.32086805, 0.67913195],
       [0.304135  , 0.695865  ],
       [0.2553639 , 0.7446361 ],
       [0.55059739, 0.44940261],
       [0.51672278, 0.48327722],
       [0.72261444, 0.27738556],
       [0.14943734, 0.85056266],
       [0.22198621, 0.77801379],
       [0.85522723, 0.14477277],
       [0.92996672, 0.07003328],
       [0.09636737, 0.90363263],
       [0.33765461, 0.66234539],
       [0.66164438, 0.33835562],
       [0.47625539, 0.52374461],
       [0.43906333, 0.56093667],
       [0.21393162, 0.78606838],
       [0.17775756, 0.82224244],
       [0.45798963, 0.54201037],
       [0.69069185, 0.30930815],
       [0.74043803, 0.25956197],
       [0.83941218, 0.16058782],
       [0.1878305 , 0.8121695 ],
       [0.54772892, 0.45227108],
       [0.78163061, 0.21836939],
       [0.64449547, 0.35550453],
       [0.78927881, 0.21072119],
       [0.89031167, 0.10968833],
       [0.25930781, 0.74069219],
       [0.70030387, 0.29969613],
       [0.38416378, 0.61583622],
       [0.78927881, 0.21072119],
       [0.70405613, 0.29594387],
       [0.64449547, 0.35550453],
       [0.73491482, 0.26508518],
       [0.47625539, 0.52374461],
       [0.53926379, 0.46073621],
       [0.6849227 , 0.3150773 ],
       [0.75656954, 0.24343046],
       [0.53934229, 0.46065771]])

In [223]:
predict_proba.shape

(140, 2)

#Save the model

In [225]:
import pickle

In [226]:
with open('model','wb') as file:
  pickle.dump(reg,file)

In [227]:
with open('scaler','wb') as file:
    pickle.dump(absenteeism_scaler, file)